var CALENDAR_STATES = Object.freeze({
    LEFT_YEAR: 0,
    RIGHT_YEAR: 1,
    LEFT_DAY: 2,
    RIGHT_DAY: 3,
    BOTH_DAY: 4,
    BOTH_CLOSED: 5, //BASE STATE
    BOTH_YEAR: 6,
    BOTH_MONTH: 7,
    LEFT_MONTH: 8,
    RIGHT_MONTH: 9,

    YEAR_MONTH: 10,
    MONTH_YEAR: 11,
    YEAR_DAY: 12,
    DAY_YEAR: 13,
    MONTH_DAY: 14,
    DAY_MONTH: 15,

});
